sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker images
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - export TAG=$(if [ "x$TRAVIS_TAG" != "x" ]; then echo "$TRAVIS_TAG"; else git
      rev-parse --short HEAD; fi)
    - travis_wait 20 docker build -t $DOCKER_REPO/base base
    - docker tag $DOCKER_REPO/base $DOCKER_REPO/base:$TAG
    - travis_wait 20 docker build -t $DOCKER_REPO/single-user single-user
    - docker tag $DOCKER_REPO/single-user $DOCKER_REPO/single-user:$TAG
    - travis_wait 20 docker build -t $DOCKER_REPO/single-user-d4science single-user-d4science
    - docker tag $DOCKER_REPO/single-user-d4science $DOCKER_REPO/single-user-d4science:$TAG
    - docker build -t $DOCKER_REPO/d4science-storage d4science-storage
    - docker tag $DOCKER_REPO/d4science-storage $DOCKER_REPO/d4science-storage:$TAG
    # tests
    - bash test.sh
    deploy:
      provider: script
      script: travis_wait 20 bash deploy.sh $DOCKER_REPO $TAG
env:
  global:
  - DOCKER_REPO=eginotebooks
