FROM quay.io/jupyter/minimal-notebook AS base

RUN mamba install --yes \
    contextily==1.6.2 \
    folium==0.19.6 \
    matplotlib==3.10.3 \
    pandas==2.3.0 \
    pillow==11.1.0 \
    numpy==2.2.6 \
    cartopy==0.24 \
    cmocean==4.0.3 \
    copernicusmarine==2.1.2 \
    dask==2025.5.1 \
    ipympl==0.9.7 \
    jupyterlab==4.4.3 \
    netcdf4==1.7.2 \
    numba==0.61.2 \
    owslib==0.33.0 \
    scipy==1.16 \
    seaborn==0.13.2 \
    xarray==2025.4.0 \
    mat73==0.65 \