FROM quay.io/jupyter/minimal-notebook AS base

RUN mamba install -y \
                  numpy==1.26.4 \
                  cartopy==0.24 \
                  cmocean==4.0.3 \
                  copernicusmarine==2.0.1 \
                  folium==0.19.5 \
                  geopandas==1.0.1 \
                  ipympl==0.9.7 \
                  ipython==9.3.0 \
                  ipywidgets==8.1.5 \
                  jupyterlab==4.3.6 \
                  matplotlib==3.10.1 \
                  netcdf4==1.7.2 \
                  openeo==0.39.1 \
                  owslib==0.33.0 \
                  pykdtree==1.4.1 \
                  rioxarray==0.18.2 \
                  scipy==1.15.2 \
                  xarray==2025.3.0 \
                  pandas==2.3.0 \
                  pyproj==3.7.1 \