FROM quay.io/jupyter/minimal-notebook AS base

RUN mamba install --yes \
    contextily==1.6.2 \
    folium==0.19.5 \
    gdown==5.2.0 \
    geopandas==1.0.1 \
    ipython==9.3.0 \
    ipywidgets==8.1.5 \
    matplotlib==3.10.1 \
    opencv==4.11.0 \
    segment-anything==1.0.1 \
    pandas==2.3.0 \
    pillow==11.1.0 \
    pytorch==2.7.0 \
    requests==2.32.3 \
    shapely==2.1.1 \
    termcolor==3.1.0 \
    torchvision==0.22.0